### ISSUE TITLE
Move Python functions into separate files

### ISSUE THREAD

**Issue by jewels86** [firelabs-io/HASM#1]
Just a readability suggestion - functions in files by themselves would make it much easier to follow.

**Comment by firelabs-io** [comment]
what you mean?

**Comment by jewels86** [comment]
In `compiler.py`, all the functions are in the same file, which makes it a little harder to read and understand. If you made a folder called `compiler` or something like that, you could give each function its own file (`eva.py`, etc) and import them into `compiler.py`.

It’s just a quick suggestion though, no hard feelings if you don’t like it.

**Comment by firelabs-io** [comment]
compiler.py as sujected is compiler, so wouln't work
however i can add smt, like target/elf64.py or smt, so the codegen function and run be on each, so i can call, thx for sujection btw

**Comment by jewels86** [comment]
Thanks for considering the suggestion!
